name: Check UTF-8

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  check_files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - run: ./check_utf8.sh 2>&1| tee failed_files.txt
        name: Run check_utf8.sh
